export const heisigMapping: { [key: string]: string } = {
  一: `one`,
  二: `two`,
  三: `three`,
  四: `four`,
  五: `five`,
  六: `six`,
  七: `seven`,
  八: `eight`,
  九: `nine`,
  十: `ten`,
  口: `mouth`,
  日: `day`,
  月: `month`,
  田: `rice field`,
  目: `eye`,
  古: `ancient`,
  胡: `recklessly`,
  叶: `leaf`,
  吾: `I (literary)`,
  朋: `companion`,
  明: `bright`,
  唱: `sing`,
  晶: `sparkling`,
  品: `goods`,
  昌: `prosperous`,
  早: `early`,
  旭: `rising sun`,
  世: `generation`,
  胃: `stomach`,
  旦: `daybreak`,
  凹: `concave`,
  凸: `convex`,
  自: `oneself`,
  白: `white`,
  百: `hundred`,
  皂: `soap`,
  旧: `old`,
  中: `middle (n. / adj.)`,
  千: `thousand`,
  舌: `tongue`,
  升: `liter`,
  丸: `pill`,
  卜: `divination`,
  占: `tell fortunes`,
  上: `above`,
  下: `below`,
  卡: `card`,
  卓: `eminent`,
  朝: `dynasty`,
  嘲: `ridicule (v.)`,
  只: `only`,
  贝: `shellfish (v.)`,
  贴: `paste`,
  贞: `chaste`,
  员: `employee`,
  儿: `youngster`,
  几: `how many?`,
  见: `see`,
  元: `beginning`,
  页: `page`,
  顽: `stubborn`,
  凡: `ordinary`,
  肌: `muscle`,
  负: `defeated (adj.)`,
  万: `ten thousand`,
  匀: `uniform (adj.)`,
  句: `sentence (n.)`,
  旬: `decameron`,
  勺: `ladle`,
  的: `bull's eye`,
  首: `heads`,
  直: `straight`,
  置: `set up`,
  具: `tool`,
  真: `true`,
  工: `work (n.)`,
  左: `left (n. / adj.)`,
  右: `right (n. / adj.)`,
  有: `possess`,
  贿: `bribe (n.)`,
  贡: `tribute`,
  项: `item`,
  刀: `sword`,
  刃: `blade`,
  切: `cut (v.)`,
  召: `summon`,
  昭: `evident`,
  则: `rule (n.)`,
  副: `vice-`,
  丁: `fourth`,
  叮: `sting (v.)`,
  可: `can (aux. v.)`,
  哥: `older brother`,
  顶: `crest`,
  乙: `second (adj.)`,
  飞: `fly (v.)`,
  子: `child`,
  孔: `cavity`,
  吼: `roar (v.)`,
  乱: `chaos`,
  了: `(-ed)`,
  女: `woman`,
  好: `good`,
  如: `be like`,
  母: `mother`,
  贯: `pierce`,
  兄: `elder brother`,
  克: `overcome (v.)`,
  小: `small`,
  少: `few`,
  吵: `noisy`,
  孙: `grandchild`,
  大: `large`,
  尖: `tip (n.)`,
  夕: `evening`,
  多: `many`,
  够: `enough`,
  外: `outside`,
  名: `name (n.)`,
  罗: `silk gauze`,
  厂: `factory`,
  厅: `hall`,
  厉: `stern`,
  厚: `thick`,
  石: `stone`,
  砂: `gravel`,
  妙: `wonderful`,
  肖: `resemble`,
  削: `peel (v.)`,
  光: `ray`,
  太: `overly`,
  省: `economize`,
  奇: `strange`,
  川: `stream (n.)`,
  州: `state (n.)`,
  顺: `obey`,
  水: `water (n.)`,
  永: `eternity`,
  脉: `blood vessels`,
  求: `request (v.)`,
  泉: `spring (n.)`,
  原: `flatlands`,
  泳: `swim`,
  洲: `continent`,
  沼: `marsh`,
  沙: `sand (n.)`,
  江: `Yangtze`,
  汁: `juice (n.)`,
  潮: `tide`,
  源: `source`,
  活: `lively`,
  消: `extinguish`,
  河: `river`,
  鱼: `fish (n.)`,
  渔: `fishing (n.)`,
  湖: `lake`,
  测: `fathom (v.)`,
  土: `soil (n.)`,
  均: `equal`,
  肚: `belly`,
  尘: `dust`,
  填: `fill in`,
  吐: `spit (v.)`,
  压: `pressure (n.)`,
  哇: `waaah!`,
  寸: `Chinese inch`,
  封: `seal (v.)`,
  时: `time`,
  寺: `Buddhist temple`,
  火: `fire (n.)`,
  灭: `destroy`,
  灰: `ashes`,
  烦: `vexed (adj.)`,
  炎: `inflammation`,
  淡: `thin (adj.)`,
  灯: `lamp`,
  点: `spot (n.)`,
  照: `illuminate`,
  里: `li`,
  量: `quantity`,
  埋: `bury`,
  黑: `black`,
  墨: `black ink`,
  冒: `risk (v.)`,
  同: `same`,
  洞: `cave`,
  丽: `lovely`,
  向: `orientation`,
  响: `echo (n.)`,
  尚: `esteem (v.)`,
  字: `character`,
  守: `guard (v.)`,
  完: `finish (v.)`,
  灾: `disaster`,
  宣: `proclaim`,
  宵: `nighttime`,
  安: `peaceful`,
  宴: `banquet`,
  寄: `mail (v.)`,
  富: `wealthy`,
  贮: `store up`,
  木: `tree`,
  林: `woods`,
  森: `forest`,
  梦: `dream (n.)`,
  机: `machine`,
  植: `plant (v.)`,
  杏: `apricot`,
  呆: `dim-witted`,
  枯: `withered`,
  村: `village`,
  相: `one another`,
  本: `notebook`,
  案: `case`,
  未: `not yet`,
  末: `last (n. / adj.)`,
  沫: `foam`,
  味: `flavor (n.)`,
  妹: `younger sister`,
  查: `investigate`,
  渣: `sediment`,
  染: `dye (v.)`,
  李: `plum`,
  桌: `table`,
  杂: `miscellaneous`,
  若: `as if`,
  草: `grass`,
  艺: `technique`,
  苦: `suffering (n.)`,
  宽: `wide`,
  莫: `nobody`,
  模: `imitate`,
  漠: `desert (n.)`,
  墓: `grave`,
  苗: `seedling`,
  瞄: `aim`,
  兆: `portent`,
  桃: `peach`,
  犬: `pooch`,
  尤: `remarkable`,
  厌: `detest`,
  状: `state of affairs`,
  妆: `put on makeup`,
  将: `General`,
  获: `seize`,
  默: `silent`,
  然: `sort of thing`,
  哭: `cry (v.)`,
  器: `utensil`,
  臭: `stinking (adj.)`,
  狗: `dog`,
  牛: `cow`,
  特: `special (adj.)`,
  告: `declare`,
  浩: `vast`,
  先: `before`,
  洗: `wash (v.)`,
  个: `individual`,
  介: `introduce`,
  界: `world`,
  茶: `tea`,
  合: `fit (v.)`,
  哈: `ha!`,
  塔: `pagoda`,
  王: `king`,
  玉: `jade`,
  宝: `treasure (n.)`,
  球: `ball`,
  现: `present (adj.)`,
  玩: `play (v.)`,
  狂: `crazy`,
  皇: `emperor`,
  煌: `resplendent`,
  呈: `submit`,
  全: `whole`,
  理: `logic`,
  主: `lord`,
  注: `pour`,
  金: `gold`,
  钟: `bell`,
  铜: `copper`,
  钓: `go fishin'`,
  针: `needle (n.)`,
  钉: `nail (n.)`,
  铭: `inscription`,
  镇: `at ease`,
  道: `way`,
  达: `reach (v.)`,
  远: `distant`,
  适: `suitable`,
  过: `cross (v.)`,
  迈: `stride`,
  迅: `speedy`,
  造: `create`,
  逃: `escape (v.)`,
  巡: `patrol (v.)`,
  选: `choose`,
  逊: `modest`,
  逛: `stroll`,
  车: `car`,
  连: `one after another`,
  莲: `lotus`,
  前: `in front`,
  剪: `shears`,
  输: `transport`,
  逾: `exceed`,
  条: `strip (n.)`,
  处: `location`,
  各: `each`,
  格: `pattern`,
  略: `abbreviation`,
  客: `guest`,
  额: `forehead`,
  夏: `summer`,
  洛: `L.A.`,
  落: `fall`,
  备: `prepare`,
  冗: `superfluous`,
  沉: `profound`,
  军: `army`,
  辉: `radiance`,
  冠: `crown`,
  坑: `pit (n.)`,
  亩: `Chinese acre`,
  高: `tall`,
  享: `enjoy`,
  熟: `ripe`,
  亭: `pavilion`,
  亮: `shiny`,
  京: `capital`,
  景: `scenery`,
  就: `at once`,
  周: `circumference`,
  士: `soldier`,
  吉: `lucky`,
  壮: `robust`,
  学: `study (v.)`,
  觉: `senses (n.)`,
  攻: `attack`,
  敌: `enemy`,
  败: `fail`,
  故: `deliberately`,
  救: `rescue (v.)`,
  敬: `revere`,
  敞: `spacious`,
  言: `say`,
  警: `police (n.)`,
  计: `plan (n.)`,
  让: `yield (n.)`,
  狱: `prison`,
  讨: `condemn`,
  训: `instruction`,
  识: `knowledge`,
  话: `talk (n.)`,
  诗: `poem`,
  语: `language`,
  调: `tune (n.)`,
  谈: `discuss`,
  式: `style (n.)`,
  试: `test`,
  戈: `halberd`,
  战: `war`,
  划: `scratch (v.)`,
  或: `or`,
  贼: `burglar`,
  载: `laden`,
  茂: `lush`,
  成: `turn into`,
  城: `city`,
  诚: `sincere`,
  威: `might (n.)`,
  咸: `salty`,
  钱: `coin (n.)`,
  浅: `shallow`,
  贱: `cheap`,
  尧: `Yao`,
  烧: `fever`,
  晓: `dawn`,
  止: `stop (v.)`,
  步: `footstep`,
  涉: `ford (v.)`,
  频: `repeatedly`,
  肯: `agree`,
  企: `look forward to`,
  武: `military (adj.)`,
  赋: `levy (n.)`,
  正: `correct (v. / adj.)`,
  证: `evidence`,
  政: `politics`,
  定: `settle on`,
  走: `walk`,
  超: `transcend`,
  越: `surpass`,
  是: `be`,
  题: `topic`,
  延: `prolong`,
  诞: `nativity`,
  建: `build`,
  楚: `clear (adj.)`,
  衣: `clothing`,
  裁: `tailor (v.)`,
  装: `attire (n.)`,
  哀: `grief`,
  袁: `Yuan`,
  初: `elementary`,
  补: `patch (v.)`,
  衬: `inner garments`,
  农: `agriculture`,
  浓: `concentrated`,
  巾: `towel`,
  帅: `commander`,
  师: `teacher`,
  狮: `lion`,
  布: `cloth`,
  帜: `streamer`,
  帽: `hat`,
  幕: `curtain`,
  棉: `cotton`,
  市: `market (n.)`,
  肺: `lungs`,
  带: `sash`,
  滞: `stagnant`,
  刺: `thorn`,
  制: `system`,
  雨: `rain`,
  雷: `thunder (n.)`,
  霜: `frost`,
  云: `cloud`,
  运: `carry`,
  冰: `ice`,
  况: `situation`,
  冲: `collide`,
  减: `reduce`,
  凉: `cool`,
  冬: `winter`,
  天: `heavens`,
  吴: `Wu`,
  娱: `amusement`,
  误: `error`,
  夭: `die young`,
  乔: `pretend`,
  桥: `bridge`,
  娇: `attractive`,
  立: `standing up (adj.)`,
  泣: `weep`,
  站: `station (n.)`,
  章: `chapter`,
  竞: `compete`,
  帝: `sovereign (n.)`,
  童: `juvenile (n.)`,
  商: `salesman`,
  滴: `drip (v.)`,
  匕: `ancient spoon`,
  北: `north`,
  背: `back (n.)`,
  比: `compare`,
  昆: `descendants`,
  混: `mix (v.)`,
  皆: `all`,
  此: `this (literary)`,
  些: `somewhat`,
  它: `it`,
  旨: `purpose`,
  脂: `grease`,
  论: `theory`,
  轮: `wheel`,
  每: `every`,
  梅: `small plum`,
  海: `sea`,
  乞: `beg`,
  吃: `eat`,
  复: `duplicate (v.)`,
  腹: `abdomen`,
  欠: `lack (v.)`,
  吹: `blow (v.)`,
  歌: `song`,
  软: `soft`,
  次: `next`,
  资: `assets`,
  姿: `looks (n.)`,
  咨: `consult with`,
  赔: `compensate`,
  培: `cultivate`,
  音: `sound`,
  暗: `dark`,
  韵: `rhyme (n.)`,
  竟: `unexpectedly`,
  镜: `mirror`,
  境: `boundary`,
  亡: `deceased (adj.)`,
  盲: `blind (adj.)`,
  妄: `absurd (adj.)`,
  望: `expect`,
  方: `direction`,
  妨: `hinder`,
  放: `release (v.)`,
  激: `excite`,
  旁: `side (n.)`,
  兑: `convert (v.)`,
  脱: `undress`,
  说: `speak`,
  曾: `formerly`,
  增: `increase (v.)`,
  赠: `make a present of`,
  也: `also`,
  她: `she`,
  地: `ground (n.)`,
  池: `pond`,
  虫: `insect`,
  虾: `shrimp`,
  独: `alone`,
  虽: `although`,
  蛇: `serpent`,
  蛋: `egg`,
  己: `self`,
  起: `begin`,
  改: `alter`,
  记: `remember`,
  已: `already`,
  包: `wrap (v.)`,
  泡: `bubbles`,
  导: `guide (v.)`,
  顾: `look back`,
  逐: `pursue`,
  家: `house (n.)`,
  场: `site`,
  汤: `soup`,
  羊: `sheep`,
  美: `beautiful`,
  洋: `ocean`,
  鲜: `fresh`,
  样: `appearance`,
  兰: `orchid`,
  烂: `spoiled`,
  差: `fall short of`,
  着: `-ing`,
  养: `raise (v.)`,
  集: `gather`,
  准: `standard (n.)`,
  谁: `who?`,
  售: `vend`,
  午: `noon`,
  许: `permit (v.)`,
  羽: `feathers`,
  习: `learn`,
  翔: `soar`,
  困: `trapped`,
  固: `solid`,
  国: `country`,
  圆: `round`,
  因: `cause (n.)`,
  烟: `smoke (n.)`,
  园: `park (n.)`,
  回: `return (v.)`,
  图: `picture (n.)`,
  广: `extensive`,
  店: `store (n.)`,
  库: `warehouse`,
  裤: `trousers`,
  床: `bed`,
  麻: `hemp`,
  庄: `hamlet`,
  心: `heart`,
  忘: `forget`,
  忍: `endure`,
  总: `general (adj.)`,
  态: `attitude`,
  志: `aspiration`,
  思: `consider`,
  恩: `kindness`,
  愿: `wish (n.)`,
  意: `idea`,
  想: `think`,
  息: `breath`,
  恐: `fear (v.)`,
  感: `feel (v.)`,
  憾: `regret (n.)`,
  忧: `worried`,
  惊: `startled`,
  怕: `dread (v.)`,
  忙: `busy (adj.)`,
  惯: `accustomed to`,
  必: `certainly`,
  手: `hand`,
  看: `look at`,
  摩: `rub`,
  拿: `hold (v.)`,
  我: `I`,
  抱: `embrace (v.)`,
  抗: `combat (v.)`,
  批: `criticize`,
  招: `beckon`,
  打: `strike (v.)`,
  指: `finger (n.)`,
  持: `support (v.)`,
  担: `assume`,
  括: `include`,
  提: `bring up`,
  挥: `brandish`,
  推: `push`,
  搅: `stir (v.)`,
  执: `clench`,
  热: `heat (n. / v.)`,
  接: `welcome (v.)`,
  挂: `hang`,
  按: `press down on`,
  掉: `drop (v.)`,
  拉: `pull`,
  啦: `!!`,
  找: `look for`,
  无: `nothing`,
  抚: `comfort (v.)`,
  开: `open (v.)`,
  研: `grind away (v.)`,
  弄: `play with`,
  异: `different`,
  鼻: `nose`,
  刑: `punishment`,
  型: `mold (v.)`,
  才: `genius`,
  财: `riches`,
  团: `troupe`,
  存: `deposit (v.)`,
  在: `at`,
  乃: `only then`,
  奶: `milk (n.)`,
  及: `catch up with`,
  吸: `inhale`,
  极: `extreme (n.)`,
  史: `history`,
  更: `even more`,
  硬: `hard`,
  又: `again`,
  圣: `holy`,
  友: `friend`,
  双: `pair`,
  汉: `Han`,
  戏: `frolic (v.)`,
  观: `observe`,
  欢: `joyous`,
  怪: `peculiar`,
  对: `that's right`,
  树: `timber`,
  难: `difficult`,
  摊: `vendor's stand`,
  投: `throw (v.)`,
  没: `not have`,
  设: `establish (v.)`,
  股: `thigh`,
  支: `offshoot`,
  技: `skill`,
  枝: `branch`,
  叔: `uncle`,
  督: `superintend`,
  寂: `lonely`,
  反: `against`,
  板: `plank`,
  返: `go back`,
  后: `behind`,
  质: `quality`,
  派: `faction`,
  乐: `music`,
  爪: `claw (n.)`,
  抓: `grab`,
  采: `pick (v.)`,
  菜: `vegetable`,
  受: `accept`,
  授: `confer`,
  爱: `love (n. / v.)`,
  么: `(suffix)`,
  雄: `grand`,
  台: `platform`,
  治: `govern`,
  始: `commence`,
  去: `go`,
  法: `method`,
  会: `meeting`,
  至: `until`,
  室: `room`,
  到: `arrive`,
  互: `mutual`,
  充: `sufficient`,
  育: `education`,
  流: `flow (v.)`,
  梳: `comb (n.)`,
  购: `purchase (v.)`,
  构: `frame (v.)`,
  山: `mountain`,
  出: `exit (v.)`,
  础: `foundation`,
  岁: `years of age`,
  密: `secret (adj.)`,
  入: `enter`,
  分: `part (n. / v.)`,
  贫: `impoverished`,
  公: `public (adj.)`,
  松: `pine tree`,
  谷: `valley`,
  浴: `bathe`,
  欲: `desire (n. / v.)`,
  容: `contain`,
  溶: `dissolve`,
  赏: `prize (n.)`,
  党: `political party`,
  常: `often`,
  堂: `main room`,
  皮: `covering (n.)`,
  波: `waves`,
  婆: `old woman`,
  破: `break (v.)`,
  被: `quilt (n.)`,
  歹: `malicious`,
  列: `line up`,
  烈: `intense`,
  死: `death`,
  葬: `inter (v.)`,
  耳: `ear`,
  取: `take`,
  趣: `interest`,
  最: `most`,
  职: `job`,
  敢: `brave (adj.)`,
  曼: `drawn out`,
  慢: `slow (adj.)`,
  漫: `overflow (v.)`,
  夫: `husband`,
  规: `regulations`,
  替: `replace`,
  失: `lose`,
  铁: `iron (n.)`,
  臣: `feudal official`,
  力: `power`,
  边: `border`,
  势: `force (n.)`,
  动: `move (v.)`,
  励: `encourage`,
  历: `experience (n. / v.)`,
  另: `another`,
  别: `don't`,
  拐: `turn (v.)`,
  男: `male (n.)`,
  功: `achievement`,
  办: `manage`,
  协: `cooperate`,
  苏: `revive`,
  为: `act (v.)`,
  奴: `slave (n.)`,
  努: `toil (v.)`,
  加: `add`,
  贺: `congratulate`,
  架: `shelf (n.)`,
  务: `tasks`,
  雾: `fog`,
  行: `line of business`,
  律: `law`,
  得: `must (aux. v.)`,
  待: `treat (v.)`,
  往: `toward`,
  德: `morality`,
  微: `tiny`,
  街: `street`,
  禾: `standing grain`,
  程: `journey (n.)`,
  和: `harmony`,
  积: `accumulate`,
  种: `species`,
  移: `shift (v.)`,
  秋: `autumn`,
  愁: `gloomy`,
  揪: `hold tight`,
  利: `profit (n.)`,
  香: `perfume (n.)`,
  季: `seasons`,
  委: `committee`,
  秀: `elegant`,
  透: `penetrate`,
  诱: `entice`,
  米: `rice`,
  粉: `powder (n.)`,
  迷: `lost`,
  谜: `riddle`,
  类: `kind (n.)`,
  来: `come`,
  数: `number (n.)`,
  楼: `multistory building`,
  竹: `bamboo`,
  笑: `laugh (v.)`,
  箱: `box (n.)`,
  等: `etc.`,
  算: `calculate`,
  答: `answer (v.)`,
  策: `strategy`,
  人: `person`,
  认: `recognize`,
  价: `price`,
  份: `portion`,
  伪: `bogus`,
  尔: `you (literary)`,
  你: `you`,
  您: `you (respectful)`,
  称: `weigh`,
  什: `what?`,
  值: `value (n.)`,
  做: `make`,
  但: `however`,
  住: `dwell`,
  位: `position (n.)`,
  件: `piece`,
  仍: `still (adv.)`,
  他: `he`,
  仅: `merely`,
  休: `rest (v.)`,
  体: `body`,
  信: `faith`,
  依: `depend on`,
  例: `example`,
  健: `healthy`,
  停: `halt (v.)`,
  倒: `upside down`,
  仁: `benevolence`,
  优: `excellent`,
  伤: `wound (n.)`,
  保: `safeguard (v.)`,
  堡: `fort`,
  付: `pay (v.)`,
  府: `government office`,
  俯: `bow one's head`,
  代: `substitute for`,
  袋: `bag (n.)`,
  化: `transform`,
  华: `splendor`,
  哗: `clamor (n.)`,
  花: `flower (n.)`,
  货: `commodities`,
  何: `whatwhichwhowherewhy?`,
  便: `convenient`,
  丈: `100 Chinese inches`,
  使: `use (v.)`,
  久: `long time`,
  内: `internal`,
  呐: `holler (v.)`,
  丙: `third`,
  柄: `handle (n.)`,
  肉: `meat`,
  腐: `rotten`,
  从: `follow`,
  众: `multitude`,
  坐: `sit`,
  座: `seat (n.)`,
  巫: `witch`,
  喝: `drink (v.)`,
  渴: `thirsty`,
  任: `appoint`,
  廷: `royal court`,
  庭: `court of law`,
  头: `head (n.)`,
  实: `reality`,
  买: `buy`,
  卖: `sell`,
  读: `read`,
  以: `by means of`,
  似: `similar`,
  并: `combine (v.)`,
  拼: `piece together`,
  吕: `spine`,
  侣: `associate (n.)`,
  荣: `glory (n.)`,
  劳: `labor (n.)`,
  营: `camp (n.)`,
  善: `virtuous`,
  年: `year`,
  夜: `night`,
  液: `liquid`,
  旅: `travel (v.)`,
  施: `execute`,
  游: `go swimming`,
  勿: `not`,
  忽: `suddenly`,
  物: `thing`,
  易: `easy`,
  赐: `grant (v.)`,
  尸: `corpse`,
  尼: `nun`,
  呢: `woolen cloth`,
  泥: `mud`,
  屋: `habitation`,
  握: `grip (v.)`,
  居: `reside`,
  锯: `saw (n.)`,
  剧: `drama`,
  据: `certificate`,
  层: `story`,
  局: `bureau`,
  尺: `ruler`,
  尽: `exhausted`,
  户: `door`,
  房: `domicile`,
  雇: `hire (v.)`,
  护: `protect`,
  示: `show (v.)`,
  社: `society`,
  礼: `ceremony`,
  视: `inspect`,
  福: `happiness`,
  标: `mark (n.)`,
  禁: `prohibit`,
  襟: `front of a garment`,
  宗: `religion`,
  崇: `worship (v.)`,
  祭: `offer sacrifice`,
  察: `scrutinize`,
  擦: `scrub`,
  由: `wherefore (n.)`,
  抽: `take out`,
  油: `oil`,
  甲: `first`,
  押: `pawn (v.)`,
  申: `express`,
  伸: `extend`,
  神: `gods`,
  果: `fruit`,
  课: `lesson`,
  颗: `granule`,
  斤: `catty (n.)`,
  听: `listen`,
  所: `place (n.)`,
  近: `near`,
  斩: `hew`,
  暂: `temporary`,
  渐: `gradually`,
  断: `sever`,
  折: `discount`,
  哲: `philosopher`,
  逝: `pass away`,
  斥: `reprimand (v.)`,
  诉: `accuse`,
  乍: `for the first time`,
  怎: `how?`,
  昨: `yesterday`,
  作: `do`,
  雪: `snow (n.)`,
  灵: `spirit`,
  妇: `married woman`,
  扫: `sweep`,
  寻: `seek`,
  急: `anxious`,
  当: `work as`,
  档: `files`,
  录: `record (v.)`,
  碌: `commonplace (adj.)`,
  争: `contend`,
  净: `clean (adj.)`,
  事: `matter`,
  唐: `Tang`,
  糖: `sugar`,
  康: `hale`,
  尹: `overseer`,
  伊: `Queen Elizabeth`,
  君: `monarch`,
  裙: `skirt (n.)`,
  群: `crowd (n.)`,
  而: `and`,
  需: `need (v.)`,
  儒: `Confucian`,
  瑞: `auspicious`,
  端: `upright`,
  曲: `bent`,
  斗: `big dipper`,
  料: `material (n.)`,
  科: `academic discipline`,
  用: `utilize`,
  确: `reliable`,
  昔: `times past`,
  借: `borrow`,
  错: `mistaken`,
  散: `scattered`,
  撒: `scatter`,
  廿: `twenty`,
  席: `mat`,
  度: `degrees`,
  渡: `ferry (n. / v.)`,
  半: `half (n. / adj.)`,
  伴: `partner`,
  胖: `fat (adj.)`,
  判: `judge (v.)`,
  眷: `dependents`,
  拳: `boxing (n.)`,
  片: `slice (n.)`,
  版: `printing plate`,
  之: `of`,
  乏: `weary`,
  眨: `blink (v.)`,
  不: `no`,
  否: `negate`,
  坏: `bad`,
  环: `ring (n.)`,
  杯: `cup`,
  还: `give back`,
  怀: `cherish`,
  矢: `dart (n.)`,
  族: `tribe`,
  知: `know`,
  智: `wisdom`,
  矛: `spear (n.)`,
  柔: `gentle`,
  揉: `knead`,
  予: `bestow`,
  序: `preface (n.)`,
  预: `beforehand`,
  野: `wild (adj.)`,
  班: `class`,
  临: `be about to`,
  坚: `firm (adj.)`,
  贤: `worthy`,
  弓: `bow (n.)`,
  引: `draw (v.)`,
  弥: `fill (v.)`,
  强: `strong`,
  弱: `weak`,
  单: `list (n.)`,
  弹: `bullet`,
  费: `expense`,
  佛: `Buddha`,
  弟: `younger brother`,
  第: `No.`,
  巧: `adroit`,
  号: `appellation`,
  身: `somebody`,
  射: `shoot (v.)`,
  谢: `thank`,
  老: `old man`,
  考: `take an exam`,
  烤: `roast (v.)`,
  与: `offer (v.)`,
  写: `write`,
  泻: `diarrhea`,
  孝: `filial piety`,
  教: `teach`,
  者: `someone`,
  著: `author (v.)`,
  猪: `pig`,
  追: `chase`,
  官: `bureaucrat`,
  管: `pipe`,
  父: `father`,
  交: `mingle`,
  效: `effect (n.)`,
  较: `relatively`,
  校: `school (n.)`,
  足: `lower leg`,
  跑: `run (v.)`,
  跳: `jump (v.)`,
  路: `path`,
  露: `dew`,
  骨: `skeleton`,
  滑: `slippery`,
  阿: `Apollo`,
  啊: `aah!`,
  随: `as you wish`,
  阳: `Yang`,
  阴: `Yin`,
  荫: `shady`,
  防: `ward off`,
  附: `attach`,
  际: `occasion (n.)`,
  阶: `stairs`,
  院: `Inst.`,
  阵: `battle formation`,
  队: `team`,
  坠: `plunge (v.)`,
  降: `descend`,
  穴: `hole`,
  究: `research`,
  突: `abruptly`,
  空: `empty`,
  控: `control (v.)`,
  深: `deep`,
  探: `spy (n.)`,
  丘: `hill`,
  兵: `troops`,
  丝: `silk`,
  织: `weave (v.)`,
  线: `line (n.)`,
  维: `maintain`,
  统: `continuum`,
  给: `give`,
  结: `tie (v.)`,
  终: `end (n.)`,
  级: `rank (n.)`,
  纪: `epoch`,
  红: `red`,
  约: `make an appointment`,
  细: `fine (adj.)`,
  纵: `vertical`,
  绿: `green`,
  经: `scripture`,
  轻: `lightweight (adj.)`,
  续: `continue`,
  继: `carry on (v.)`,
  药: `medicine`,
  系: `lineage`,
  紧: `tight`,
  却: `withdraw`,
  脚: `foot`,
  服: `apparel`,
  报: `newspaper`,
  命: `fate`,
  贸: `trade (n.)`,
  留: `stay (v.)`,
  溜: `slide (v.)`,
  聊: `chat (v.)`,
  柳: `willow`,
  节: `holiday`,
  卫: `defend`,
  令: `orders (n.)`,
  冷: `cold`,
  零: `zero`,
  领: `collar (n.)`,
  通: `communicate`,
  勇: `courageous`,
  仓: `storehouse`,
  枪: `gun`,
  创: `initiate (v.)`,
  犯: `criminal (n.)`,
  危: `danger`,
  脆: `fragile`,
  印: `print (n. / v.)`,
  酒: `liquor`,
  配: `distribute`,
  酋: `chieftain`,
  尊: `venerate (v.)`,
  遵: `abide by`,
  豆: `beans`,
  短: `short`,
  厨: `kitchen`,
  鼓: `drum`,
  喜: `joyful`,
  血: `blood`,
  盖: `lid`,
  温: `temperature`,
  监: `supervise`,
  篮: `basket`,
  蓝: `blue`,
  银: `silver`,
  跟: `heel (n. / v.)`,
  很: `very`,
  根: `root (n.)`,
  即: `immediately`,
  退: `retreat (v.)`,
  腿: `leg`,
  限: `limit (n. / v.)`,
  眼: `eyelet`,
  良: `high-quality (adj.)`,
  浪: `breakers`,
  娘: `mom`,
  食: `food`,
  饭: `meal`,
  餐: `dine`,
  馆: `Bldg.`,
  既: `since`,
  概: `approximate (adj.)`,
  平: `even (adj.)`,
  评: `evaluate`,
  坪: `level ground`,
  乎: `ooh!`,
  呼: `shout (v.)`,
  希: `hope (v.)`,
  稀: `scarce`,
  杀: `kill`,
  风: `wind (n.)`,
  讽: `mock`,
  冈: `ridge of a hill`,
  刚: `just now`,
  网: `net (n.)`,
  画: `drawing`,
  凶: `cruel`,
  胸: `bosom`,
  脑: `brain`,
  恼: `annoyed`,
  离: `leave (v.)`,
  禽: `fowl`,
  义: `righteousness`,
  议: `deliberate (v.)`,
  蚁: `ant`,
  辛: `peppery`,
  辩: `dispute (v.)`,
  辟: `repudiate`,
  壁: `partition (n.)`,
  避: `evade`,
  亲: `relatives`,
  新: `new`,
  薪: `fuel`,
  幸: `good fortune`,
  叫: `call (v.)`,
  收: `receive`,
  亥: `sign of the hog`,
  核: `nucleus`,
  孩: `tot`,
  刻: `carve`,
  该: `should`,
  术: `art`,
  述: `narrate`,
  襄: `aid (v.)`,
  壤: `territory`,
  寒: `frigid`,
  赛: `competition`,
  毒: `poison (n.)`,
  麦: `wheat`,
  素: `vegetarian diet`,
  青: `blue or green`,
  精: `refined`,
  请: `invite`,
  情: `feelings`,
  睛: `eyeball`,
  清: `pure`,
  静: `quiet`,
  责: `responsibility`,
  绩: `accomplishments`,
  表: `surface (n.)`,
  生: `life`,
  星: `star (n.)`,
  姓: `surname`,
  性: `sex`,
  胜: `victory`,
  丰: `plentiful`,
  害: `harm (n.)`,
  割: `cut off (v.)`,
  慧: `intelligent`,
  韦: `tanned hide`,
  围: `surround`,
  伟: `great`,
  春: `springtime`,
  泰: `tranquil`,
  奉: `proffer (v.)`,
  棒: `cudgel (n.)`,
  击: `beat (v.)`,
  陆: `land`,
  专: `specialty`,
  传: `spread (v.)`,
  转: `rotate`,
  勤: `diligent`,
  谨: `careful`,
  垂: `droop`,
  锤: `hammer (n.)`,
  睡: `sleep (v.)`,
  今: `now`,
  含: `harbor (v.)`,
  念: `miss (v.)`,
  东: `east`,
  栋: `building`,
  冻: `freeze (v.)`,
  陈: `exhibit (v.)`,
  练: `practice (v.)`,
  拣: `opt for`,
  西: `west`,
  要: `want (v.)`,
  腰: `waist`,
  票: `ticket`,
  漂: `drift (v.)`,
  贾: `merchant`,
  南: `south`,
  门: `gate`,
  们: `(plural)`,
  闲: `leisure`,
  问: `ask`,
  间: `interval`,
  简: `simple`,
  闻: `hear`,
  非: `non-`,
  排: `row (n.)`,
  罪: `guilt`,
  靠: `lean on`,
  侯: `marquis`,
  候: `wait (v.)`,
  决: `decide`,
  快: `fast (adj.)`,
  块: `lump (n.)`,
  筷: `chopsticks`,
  干: `dry (adj.)`,
  岸: `shore`,
  旱: `drought`,
  赶: `hurry (v.)`,
  于: `Yu`,
  宇: `eaves`,
  余: `excess`,
  除: `eliminate`,
  途: `route (n.)`,
  束: `bundle up`,
  速: `quick`,
  辣: `spicy hot`,
  整: `entire`,
  重: `heavy`,
  懂: `understand`,
  病: `illness`,
  痛: `ache (v.)`,
  疯: `insane`,
  区: `region`,
  枢: `hub`,
  欧: `Europe`,
  医: `physician`,
  仰: `look up to`,
  迎: `greet`,
  登: `ascend`,
  发: `send out`,
  废: `discard (v.)`,
  形: `shape (n.)`,
  影: `shadow (n.)`,
  彩: `hue`,
  须: `have to`,
  参: `participate`,
  惨: `wretched`,
  修: `repair (v.)`,
  珍: `rare`,
  产: `products`,
  彦: `erudite`,
  颜: `countenance (n.)`,
  文: `literature`,
  蚊: `mosquito`,
  这: `this`,
  齐: `identical`,
  济: `relieve`,
  率: `rate (n.)`,
  摔: `tumble (v.)`,
  央: `center`,
  英: `England`,
  唤: `call out`,
  换: `exchange (v.)`,
  巴: `crust`,
  把: `grasp (v.)`,
  爸: `papa`,
  吧: `bar (n.)`,
  色: `color (n.)`,
  绝: `discontinue`,
  艳: `gorgeous`,
  甘: `sweet`,
  某: `such and such (adj.)`,
  其: `his-hers-its-theirs`,
  期: `period of time`,
  基: `base (n.)`,
  甚: `tremendously`,
  斯: `Sphinx`,
  贵: `expensive`,
  遗: `bequeath`,
  舞: `dance (n. / v.)`,
  且: `moreover`,
  姐: `older sister`,
  组: `group (n.)`,
  祖: `ancestor`,
  助: `assist (v.)`,
  普: `universal`,
  业: `profession`,
  显: `obvious`,
  亚: `Asia`,
  恶: `evil`,
  严: `strict`,
  共: `together`,
  供: `supply (n. / v.)`,
  巷: `lane`,
  港: `port (n.)`,
  井: `well (n.)`,
  讲: `lecture (v.)`,
  进: `advance (v.)`,
  角: `angle`,
  解: `untie`,
  嘴: `orifice`,
  再: `once more`,
  扁: `flat (adj.)`,
  篇: `piece of writing`,
  编: `compile`,
  典: `canon`,
  氏: `family name`,
  纸: `paper`,
  昏: `dusk`,
  婚: `marriage`,
  低: `low`,
  底: `bottom`,
  民: `people`,
  眠: `slumber (n.)`,
  甫: `Fu`,
  辅: `supplement (v.)`,
  博: `knowledgeable`,
  搏: `wrestle`,
  都: `metropolis`,
  部: `department`,
  郎: `young man`,
  帮: `help (v.)`,
  乡: `countryside`,
  段: `section (n.)`,
  锻: `forge (v.)`,
  幻: `unreal`,
  司: `take charge of`,
  词: `word (n.)`,
  书: `book`,
  舟: `boat`,
  船: `ship (n.)`,
  般: `sort (n.)`,
  盘: `tray`,
  搬: `relocate`,
  瓜: `melon`,
  孤: `orphan`,
  益: `benefit (n.)`,
  假: `vacation (n.)`,
  暇: `spare time`,
  气: `air (n.)`,
  汽: `vapor`,
  面: `face-to-face`,
  革: `leather (n.)`,
  鞋: `shoes`,
  勒: `tighten`,
  馨: `fragrant`,
  声: `voice (n.)`,
  承: `undertake`,
  蒸: `steam (v.)`,
  牙: `tooth`,
  穿: `pass through`,
  呀: `wow!`,
  释: `explain`,
  番: `try (n.)`,
  翻: `turn over`,
  播: `broadcast (v.)`,
  毛: `fur`,
  尾: `tail`,
  笔: `pen`,
  托: `entrust`,
  宅: `dwelling (n.)`,
  展: `unfold`,
  丧: `funeral`,
  长: `long`,
  张: `stretch (v.)`,
  涨: `swell (v.)`,
  雁: `wild goose`,
  应: `ought to`,
  兴: `excitement`,
  举: `lift up`,
  检: `examine`,
  脸: `face (n.)`,
  险: `perilous`,
  鸟: `bird`,
  鸡: `chicken`,
  鹰: `hawk`,
  鸭: `duck (n.)`,
  岛: `island`,
  遇: `encounter (v.)`,
  缺: `deficient`,
  遥: `remote (adj.)`,
  摇: `shake (v.)`,
  兔: `rabbit`,
  逸: `flee`,
  免: `avoid`,
  晚: `nightfall`,
  象: `elephant`,
  像: `likeness`,
  马: `horse`,
  妈: `mama`,
  吗: `yes or no`,
  骂: `scold (v.)`,
  验: `check (v.)`,
  骑: `ride (v.)`,
  虎: `tiger`,
  虑: `ponder`,
  虚: `false`,
  鹿: `deer`,
  熊: `bear (n.)`,
  能: `ability`,
  寅: `sign of the tiger`,
  演: `perform`,
  辰: `sign of the dragon`,
  晨: `morning`,
  关: `shut (v.)`,
  送: `deliver`,
  联: `unite`,
  鬼: `ghost`,
  魔: `demon`,
  龙: `dragon`,
  袭: `raid (v.)`,
  那: `that`,
  哪: `which?`,
  两: `dos`,
  俩: `duo`,
  满: `full`,
  县: `county`,
  悬: `suspend`,
  窗: `window`,
  电: `electricity`,
  掩: `conceal`,
  丑: `clown`,
  扭: `twist (v.)`,
  黄: `yellow`,
  横: `horizontal`,
  赤: `crimson`,
  亦: `likewise`,
  弯: `curved (adj.)`,
  湾: `bay (n.)`,
  恋: `be enamored of`,
  变: `change (v.)`,
  卑: `lowly`,
  牌: `brand (n.)`,
  套: `cover (n.)`,
  曰: `sayeth`,
  属: `belong to`,
  叭: `trumpet (n.)`,
  咕: `mutter`,
  胆: `gall bladder`,
  咱: `we (inclusive)`,
  肿: `swollen`,
  串: `string together`,
  吓: `terrify`,
  罩: `overspread (v.)`,
  兽: `beast`,
  嚣: `hubbub`,
  矗: `stand straight`,
  颠: `invert`,
  巩: `strengthen`,
  叨: `talkative`,
  刮: `scrape (v.)`,
  盯: `stare at`,
  呵: `rebuke (v.)`,
  姑: `father's sister`,
  婴: `baby`,
  姆: `nanny`,
  兢: `cautious`,
  奋: `exert oneself`,
  夹: `press from both sides`,
  颊: `cheek`,
  厕: `toilet`,
  硕: `big`,
  砌: `lay brick`,
  哨: `whistle (n.)`,
  晃: `sway (v.)`,
  泪: `tears`,
  泄: `discharge (v.)`,
  泊: `moor (v.)`,
  沾: `soak`,
  渺: `insignificant`,
  汰: `get rid of`,
  咏: `chant (v.)`,
  腺: `gland`,
  鲁: `Lu`,
  坦: `level (adj.)`,
  坝: `dam (n.)`,
  涯: `bank (n.)`,
  娃: `newborn (n.)`,
  肘: `elbow (n.)`,
  碍: `obstruct`,
  夺: `take by force`,
  灼: `scorch`,
  炒: `stir-fry (v.)`,
  灶: `cooking stove`,
  哩: `mile`,
  厘: `smidgen`,
  鲤: `carp (n.)`,
  嘿: `Hey!`,
  熏: `treat with smoke`,
  丹: `cinnabar red`,
  炯: `shining`,
  晌: `part of the day`,
  淌: `trickle (v.)`,
  宁: `calm (adj.)`,
  寡: `widowed`,
  喧: `boisterous`,
  棚: `shed (n.)`,
  柏: `cypress`,
  朴: `plain (adj.)`,
  朵: `flouds`,
  杠: `thick stick`,
  椅: `chair`,
  樱: `cherry`,
  梢: `treetops`,
  杜: `prevent`,
  杰: `outstanding`,
  桐: `paulownia`,
  宋: `Song Dynasty`,
  桂: `cassia-bark tree`,
  淋: `drench`,
  焚: `burn (v.)`,
  厢: `side room`,
  昧: `obscure (adj./v.)`,
  朱: `vermillion`,
  株: `tree trunk`,
  萌: `bud (v.)`,
  苟: `careless`,
  苛: `exacting`,
  萝: `edible root`,
  膜: `membrane`,
  暮: `sunset`,
  寞: `solitary`,
  猫: `cat`,
  狭: `narrow (adj.)`,
  狸: `raccoon dog`,
  犹: `just like`,
  燃: `ignite`,
  咒: `curse (v.)`,
  嗅: `sniff (v.)`,
  牢: `jail`,
  牡: `dude`,
  宪: `constitution`,
  赞: `succor (v.)`,
  伞: `umbrella`,
  舍: `abode`,
  啥: `wha?`,
  洽: `in agreement`,
  旺: `thriving`,
  碧: `green jade`,
  琐: `trivial`,
  汪: `tearful`,
  枉: `crooked`,
  珠: `pearl`,
  噩: `shocking`,
  栓: `plug (n.)`,
  柱: `pillar`,
  钥: `key`,
  钻: `drill (n./v.)`,
  钞: `paper money`,
  锁: `lock (n./v.)`,
  销: `put up for sale`,
  锣: `gong`,
  迫: `compel`,
  迁: `resituate`,
  逼: `press (v.)`,
  辽: `far away`,
  逻: `make the rounds`,
  逞: `flaunt`,
  轨: `rails`,
  轧: `flatten`,
  辐: `spokes`,
  链: `chain (n.)`,
  煎: `saute (v.)`,
  喻: `figure of speech`,
  榆: `elm`,
  胳: `upper limb`,
  厦: `skyscraper (v.)`,
  牵: `lead along`,
  浑: `muddled`,
  晕: `dizzy`,
  炕: `brick-heated bed`,
  膏: `ointment`,
  淳: `honest`,
  亨: `go smoothly`,
  哼: `hum (v.)`,
  鲸: `whale`,
  壳: `shell (n.)`,
  洁: `spotless`,
  枚: `small objects`,
  牧: `herd (v.)`,
  玫: `rose`,
  敦: `candid`,
  墩: `mound`,
  瞻: `look upward`,
  谓: `meaning`,
  询: `inquire`,
  讥: `deride`,
  罚: `penalize`,
  订: `place an order`,
  谅: `forgive`,
  诺: `promise (n.)`,
  讯: `interrogate`,
  谍: `espionage`,
  碟: `saucer`,
  贰: `II`,
  腻: `sick and tired of`,
  嘎: `caw (n.)`,
  域: `domain`,
  栽: `sow (v.)`,
  戚: `kin`,
  蔑: `despise`,
  喊: `yell (v.)`,
  溅: `splatter (v.)`,
  浇: `sprinkle`,
  涩: `astringent`,
  址: `address (n.)`,
  赴: `go to`,
  趟: `trip`,
  堤: `dike`,
  津: `Tianjin`,
  键: `keyboard keys`,
  婿: `son-in-law`,
  袜: `socks`,
  衰: `decline (v.)`,
  衷: `innermost feelings`,
  猿: `ape`,
  吊: `dangle`,
  币: `currency`,
  帕: `handkerchief`,
  帖: `note (n.)`,
  帆: `sail (n.)`,
  幅: `width of cloth`,
  锦: `brocade`,
  沛: `copious`,
  柿: `persimmon`,
  棘: `thorn bushes`,
  蕾: `flower bud`,
  尝: `taste (v.)`,
  坛: `altar`,
  枣: `jujube`,
  吞: `gulp down`,
  妖: `bewitching`,
  沃: `fertile`,
  袄: `short Chinese-style coat`,
  轿: `sedan chair`,
  垃: `garbage`,
  啼: `weep aloud`,
  蒂: `fruit stem`,
  顷: `100 Chinese acres`,
  匙: `spoon (n.)`,
  乖: `well-behaved`,
  乘: `hitch a ride`,
  剩: `leftover (adj.)`,
  毕: `complete (v.)`,
  棍: `club (n.)`,
  谐: `in accord`,
  柴: `firewood`,
  沦: `sink (v.)`,
  敏: `quick-witted`,
  霉: `mildew (n.)`,
  迄: `so far`,
  砍: `chop (v.)`,
  坎: `hump (n.)`,
  炊: `cook (v.)`,
  钦: `think highly of`,
  剖: `cut open`,
  菩: `bodhisattva`,
  黯: `tenebrous`,
  赢: `win (v.)`,
  芒: `mango`,
  荒: `wasteland`,
  谎: `lie (n.)`,
  茫: `boundless`,
  坊: `workshop`,
  芳: `aromatic`,
  访: `call on`,
  淤: `silt`,
  熬: `stew (v.)`,
  膀: `upper arm`,
  磅: `pound (n.)`,
  榜: `roster`,
  锐: `sharp`,
  虹: `rainbow`,
  蝠: `bat (n.)`,
  浊: `turbid`,
  蝗: `locust`,
  蛙: `frog`,
  烛: `candle`,
  茧: `cocoon`,
  蚕: `silkworm`,
  胞: `placenta`,
  炮: `cannon`,
  袍: `robe (n.)`,
  雹: `hail`,
  豪: `unrestrained`,
  啄: `peck (v.)`,
  琢: `chisel (v.)`,
  遂: `satisfy`,
  嫁: `marry`,
  肠: `intestines`,
  杨: `poplar`,
  烫: `scald`,
  荡: `licentious`,
  姜: `ginger`,
  详: `detailed`,
  羡: `envy (v.)`,
  栏: `railing`,
  拦: `impede`,
  唯: `solely`,
  雀: `sparrow`,
  堆: `pile (n./v.)`,
  雕: `sculpture`,
  截: `lop off`,
  霍: `all at once`,
  雌: `feminine`,
  焦: `apprehensive`,
  瞧: `lay eyes on`,
  礁: `reef`,
  蕉: `banana`,
  翘: `turn upward`,
  塌: `fall down`,
  翰: `writing brush`,
  耀: `show off (v.)`,
  戳: `jab (v.)`,
  咽: `throat`,
  姻: `in-law`,
  墙: `wall`,
  旷: `expansive`,
  矿: `mine (n.)`,
  庆: `celebrate`,
  嘛: `(pause marker)`,
  磨: `grind`,
  脏: `dirty`,
  赃: `stolen goods`,
  桩: `stake (n.)`,
  忠: `loyal`,
  恕: `pardon (v.)`,
  惑: `be bewildered`,
  愈: `more and more`,
  惠: `favor (n.)`,
  忌: `shun`,
  患: `troubles`,
  惹: `provoke`,
  恒: `permanent`,
  悟: `realize`,
  悼: `mourn`,
  惧: `be frightened`,
  慎: `prudent`,
  惰: `indolent`,
  恢: `immense`,
  惶: `fearful`,
  忆: `recall (v.)`,
  悄: `noiseless`,
  恍: `all of a sudden`,
  恰: `just right`,
  愉: `overjoyed`,
  怔: `terror-stricken`,
  怖: `be scared of`,
  慌: `nervous`,
  愣: `dumbfounded`,
  悦: `delighted`,
  憎: `loathe`,
  惟: `thinking`,
  悔: `be sorry about`,
  慕: `admire`,
  添: `augment`,
  媳: `daughter-in-law`,
  熄: `put out`,
  泌: `secrete`,
  瑟: `Chinese harp`,
  蜜: `honey`,
  蛾: `moth`,
  扒: `pick pockets (v.)`,
  扣: `button (n./v.)`,
  拍: `racquet`,
  啪: `clapping sound`,
  扑: `pounce on`,
  拘: `detain`,
  损: `damage (v.)`,
  拓: `pioneer (v.)`,
  扛: `carry over the shoulder`,
  扎: `prick (v.)`,
  拇: `thumb`,
  捎: `bring to`,
  抄: `copy (v.)`,
  垫: `pad (n./v.)`,
  挚: `earnest`,
  捏: `pinch (v.)`,
  拧: `tweak (v.)`,
  抹: `smear on`,
  摸: `grope`,
  描: `describe`,
  挑: `foment`,
  扰: `harass`,
  搞: `engage in`,
  拴: `tether (v.)`,
  拾: `tidy up`,
  搭: `put up`,
  掠: `pillage (v.)`,
  拭: `wipe away`,
  挠: `chafe`,
  扯: `yank (v.)`,
  撞: `bump into`,
  摘: `handpick`,
  拖: `drag (v.)`,
  扬: `publicize`,
  搓: `massage (v.)`,
  捆: `lash together`,
  扩: `enlarge`,
  撼: `joggle (v.)`,
  挟: `coerce`,
  擅: `act without authority`,
  颤: `tremble`,
  戒: `take precautions against`,
  械: `weapon`,
  诫: `warn`,
  莽: `rude`,
  奔: `dash (v.)`,
  喷: `spurt (v.)`,
  愤: `indignation`,
  材: `stuff (n.)`,
  荐: `recommend`,
  孕: `pregnant`,
  扔: `throw away`,
  携: `take along`,
  圾: `trash (n.)`,
  梗: `stalk (n.)`,
  叹: `sigh (v.)`,
  叉: `fork (n.)`,
  权: `authority`,
  寇: `outlaw (n.)`,
  敲: `knock (v.)`,
  轰: `rumble (n./v.)`,
  滩: `beach (n.)`,
  毅: `resolute`,
  肢: `limb`,
  妓: `prostitute`,
  歧: `fork in the road`,
  翅: `fins`,
  淑: `graceful`,
  椒: `spice plant`,
  盾: `shield (n.)`,
  贩: `peddler`,
  扳: `tug (v.)`,
  烁: `luminous`,
  觅: `try to find`,
  妥: `appropriate (adj.)`,
  豹: `leopard`,
  貌: `mein`,
  睬: `notice (v.)`,
  允: `consent (v.)`,
  宏: `magnificent`,
  垒: `baseball base`,
  胎: `fetus`,
  怠: `negligent`,
  怡: `cheerful`,
  冶: `smelt (v.)`,
  抬: `elevate`,
  罢: `cease`,
  摆: `put in order`,
  丢: `mislay`,
  致: `bring about`,
  弃: `forsake`,
  撤: `remove`,
  硫: `sulfur`,
  琉: `glaze (n.)`,
  疏: `sparse`,
  蔬: `veggies`,
  勾: `cross out`,
  沟: `ditch (n.)`,
  钩: `hook (n./v.)`,
  崩: `crumble`,
  岩: `rock`,
  峭: `precipitous`,
  崎: `rugged`,
  崖: `cliff`,
  灿: `brilliant`,
  炭: `charcoal`,
  碳: `carbon`,
  岂: `(rhetorical question)`,
  凯: `triumphant`,
  峡: `gorge (n.)`,
  崔: `Cui`,
  摧: `wreck (v.)`,
  逆: `go against`,
  溯: `go upstream`,
  塑: `plastic (n.)`,
  盼: `await hopefully`,
  颁: `promulgate`,
  芬: `essence`,
  扮: `play the part of`,
  岔: `diverge`,
  颂: `extol`,
  讼: `litigate`,
  滚: `trundle (v.)`,
  翁: `elderly man`,
  嗡: `buzzing (n.)`,
  裕: `abundant`,
  榕: `banyan`,
  熔: `fuse (v.)`,
  裳: `raiment`,
  掌: `palm of the hand`,
  撑: `prop up`,
  膛: `chest`,
  颇: `quite`,
  坡: `slope (n.)`,
  披: `drape over the shoulders`,
  菠: `spinach`,
  歼: `annihilate`,
  殖: `breed (v.)`,
  殊: `dissimilar`,
  残: `incomplete`,
  咧: `grin (v.)`,
  裂: `crack (v.)`,
  毙: `die a violent death`,
  耿: `dedicated`,
  辑: `edit`,
  耻: `shame (n.)`,
  摄: `take a photo`,
  聪: `smart`,
  娶: `take a wife`,
  蔓: `creeping vine`,
  肤: `skin (n.)`,
  扶: `lend a hand`,
  潜: `submerge`,
  卧: `for sleeping`,
  藏: `hide (v.)`,
  熙: `splendid`,
  勋: `merit (n.)`,
  劣: `inferior`,
  募: `recruit (v.)`,
  劝: `advise`,
  劫: `plunder (v.)`,
  抛: `toss (v.)`,
  胁: `threaten`,
  怒: `anger (n.)`,
  茄: `eggplant`,
  彻: `thorough`,
  征: `solicit`,
  惩: `chasten`,
  徒: `follower`,
  徊: `undecided`,
  役: `service`,
  循: `comply with`,
  彼: `the other`,
  衍: `develop`,
  衡: `weight`,
  衔: `title`,
  秃: `bald`,
  颓: `decrepit`,
  秒: `seconds`,
  稍: `a little (adj.)`,
  稣: `rise again`,
  稿: `draft (n.)`,
  稠: `dense`,
  颖: `clever`,
  稼: `crops`,
  税: `tax (n.)`,
  稚: `immature`,
  菌: `fungus`,
  穗: `ear of grain`,
  秘: `confidential`,
  私: `private (adj.)`,
  秩: `order (n.)`,
  锹: `shovel (n.)`,
  梨: `pear`,
  犁: `plow (n.)`,
  萎: `wilt`,
  黏: `sticky`,
  黎: `host (n.)`,
  膝: `knees`,
  漆: `wall paint`,
  锈: `rust (n./v.)`,
  眯: `squint (v.)`,
  糊: `batter`,
  粘: `glue (v.)`,
  奥: `of great depth`,
  澳: `deep inlet`,
  懊: `remorseful`,
  菊: `chrysanthemum`,
  渊: `abyss`,
  粱: `fine millet`,
  梁: `roof beam`,
  糙: `rough`,
  粒: `grain`,
  糕: `cake`,
  蔽: `shelter (n.)`,
  憋: `suppress`,
  撇: `cast aside`,
  弊: `fraud`,
  莱: `lambsquarters`,
  搂: `cuddle`,
  筑: `construct`,
  箩: `bamboo basket`,
  笨: `stupid`,
  筒: `tube`,
  箭: `arrow`,
  筛: `sift`,
  筋: `tendon`,
  伍: `V`,
  仇: `animosity`,
  倡: `start (v.)`,
  伯: `father's older brother`,
  仲: `mid-`,
  仆: `servant`,
  估: `estimate (v.)`,
  侦: `detect`,
  俱: `altogether (adv.)`,
  佑: `bless`,
  佐: `assistant`,
  侧: `lateral (adj.)`,
  亿: `one hundred million`,
  仔: `meticulous`,
  倚: `count on`,
  俏: `comely`,
  佳: `superb`,
  侍: `serve (n.)`,
  伙: `mate`,
  倘: `if`,
  宿: `stay overnight`,
  伏: `bend over`,
  袱: `wrapping cloth (v.)`,
  偷: `steal`,
  偿: `repay`,
  伐: `fell`,
  佩: `wear at the waist`,
  侨: `live abroad`,
  倾: `incline (v.)`,
  伦: `human relationships`,
  侮: `insult (v.)`,
  倍: `times`,
  仿: `mimic (v.)`,
  傲: `haughty`,
  僧: `Buddhist monk`,
  囚: `prisoner`,
  悠: `without haste`,
  侄: `nephew`,
  仙: `immortal (n.)`,
  傍: `close to`,
  催: `prod (v.)`,
  俗: `custom`,
  侠: `chivalrous person`,
  俄: `Russia`,
  聚: `assemble`,
  符: `symbol`,
  贷: `loan (n.)`,
  荷: `Holland`,
  杖: `cane`,
  仗: `battle (n.)`,
  丛: `thicket`,
  耸: `shrug (v.)`,
  挫: `frustrate`,
  诬: `charge falsely`,
  葛: `kudzu`,
  褐: `brown`,
  竭: `use up`,
  歇: `take a rest`,
  揭: `reveal`,
  淫: `promiscuous`,
  凭: `proof`,
  挺: `erect (adj.)`,
  赎: `redeem`,
  瓦: `tile`,
  瓷: `porcelain`,
  拟: `simulate`,
  瓶: `bottle`,
  宫: `palace`,
  铝: `aluminum`,
  萤: `firefly`,
  莹: `lustrous`,
  蒙: `Mongolia`,
  朦: `dim (adj.)`,
  捞: `scoop up`,
  旋: `whirl (v.)`,
  吻: `kiss (v.)`,
  匆: `hurriedly`,
  葱: `onion`,
  锡: `tin`,
  惕: `watchful`,
  卢: `Louvre`,
  屉: `drawer`,
  屑: `bits`,
  尿: `urine`,
  犀: `rhinoceros`,
  迟: `tardy`,
  刷: `brush (n./v.)`,
  漏: `leak (v.)`,
  屁: `fart (n.)`,
  屈: `knuckle under`,
  掘: `excavate`,
  履: `footwear`,
  屎: `excrement`,
  屡: `time and again`,
  屏: `folding screen`,
  眉: `eyebrows`,
  媚: `flatter`,
  昼: `daylight`,
  启: `enlighten`,
  肩: `shoulder (n.)`,
  妒: `jealous of`,
  炉: `stove`,
  芦: `reeds`,
  扇: `fan (n.)`,
  奈: `can't help but`,
  款: `funds`,
  凛: `chilly`,
  祟: `evil spirit`,
  祝: `wish well`,
  祥: `propitious`,
  蔚: `luxuriant`,
  慰: `console (v.)`,
  蒜: `garlic`,
  棕: `palm tree`,
  宙: `universe`,
  轴: `axle`,
  袖: `sleeve`,
  庙: `temple (adj.)`,
  笛: `flute`,
  届: `fall due`,
  呻: `groan`,
  坤: `female`,
  审: `painstaking`,
  婶: `auntie`,
  畅: `smooth`,
  巢: `nest (n.)`,
  棵: `flora`,
  裸: `naked`,
  裹: `envelop`,
  析: `analyze`,
  晰: `distinct`,
  芹: `celery`,
  祈: `supplicate`,
  欣: `elated`,
  掀: `uncover`,
  惭: `conscience-stricken`,
  崭: `towering`,
  浙: `Zhejian Province`,
  誓: `vow (n./v.)`,
  拆: `take apart`,
  炸: `blow up`,
  诈: `swindle`,
  归: `come back`,
  皱: `wrinkles`,
  煞: `goblin`,
  趋: `hasten`,
  雏: `chick`,
  浸: `immerse`,
  寝: `get some shuteye`,
  侵: `invade`,
  缘: `reason (n.)`,
  稳: `stable (adj.)`,
  挡: `fend off`,
  剥: `peel off`,
  秉: `wield`,
  妻: `wife`,
  凄: `miserable`,
  捷: `nimble`,
  肃: `solemn`,
  啸: `howl (v.)`,
  萧: `desolate`,
  兼: `double (adj.)`,
  赚: `earn`,
  嫌: `dislike (v.)`,
  谦: `unassuming`,
  歉: `apology`,
  廉: `inexpensive`,
  镰: `sickle`,
  睁: `unshut (v.)`,
  挣: `struggle (v.)`,
  筝: `Chinese zither`,
  塘: `pool (n.)`,
  隶: `bondservant`,
  逮: `arrest (v.)`,
  慷: `generous`,
  糠: `chaff`,
  笋: `bamboo shoot`,
  耍: `mess around`,
  耐: `-proof`,
  喘: `wheeze`,
  揣: `conjecture (v.)`,
  槽: `trough`,
  遭: `meet with`,
  糟: `messed up`,
  抖: `quiver (v.)`,
  惜: `rue (v.)`,
  措: `arrange`,
  腊: `dried meat`,
  蜡: `wax (n.)`,
  猎: `hunt (v.)`,
  燕: `swallow (n.)`,
  遮: `screen (v.)`,
  畔: `littoral (n.)`,
  拌: `blend (v.)`,
  叛: `betray`,
  券: `voucher`,
  藤: `rattan`,
  鼎: `old cooking pot`,
  芝: `sesame`,
  贬: `devalue`,
  泛: `nonspecific`,
  歪: `askew`,
  矫: `rectify`,
  矮: `short of stature`,
  唉: `sigh--ay-ay`,
  埃: `fine dust`,
  挨: `suffer`,
  簇: `cluster (n.)`,
  茅: `thatch (n.)`,
  橘: `tangerine`,
  舒: `relax`,
  览: `view (v.)`,
  揽: `take on`,
  肾: `kidneys`,
  竖: `perpendicular`,
  弘: `noble`,
  夷: `barbarian`,
  姨: `maternal aunt`,
  疆: `dividing line`,
  僵: `stiff (adj.)`,
  粥: `porridge`,
  蝉: `cicada`,
  褝: `meditation`,
  沸: `bring to a boil`,
  拂: `caress (v.)`,
  剃: `shave (v.)`,
  递: `hand over`,
  梯: `ladder`,
  涕: `snot`,
  朽: `decayed`,
  聘: `employ (v.)`,
  姊: `elder sister`,
  亏: `loss`,
  污: `filthy`,
  夸: `brag`,
  垮: `collapse (v.)`,
  挎: `carry on the arm`,
  鳄: `crocodile`,
  愕: `stunned`,
  躺: `lie down`,
  躲: `dodge (v.)`,
  躬: `stoop (v.)`,
  嗜: `hanker`,
  姥: `maternal grandmother`,
  拷: `flog`,
  屿: `islet`,
  暑: `summer heat`,
  睹: `behold`,
  署: `add your John Hancock`,
  薯: `yam`,
  赌: `gamble (v.)`,
  奢: `extravagant`,
  堵: `stop up`,
  煮: `boil (v.)`,
  诸: `various`,
  储: `put in storage`,
  屠: `slaughter`,
  棺: `coffin`,
  爹: `dad`,
  斧: `axe`,
  咬: `bite (v.)`,
  胶: `gum`,
  狡: `sly`,
  捉: `catch (v.)`,
  促: `urge (v.)`,
  趴: `prostrate oneself`,
  踏: `trample`,
  践: `tread on`,
  跃: `leap (v.)`,
  蹄: `hoof`,
  踩: `step on`,
  蹦: `hop (v.)`,
  跌: `slump (v.)`,
  踢: `kick (v.)`,
  踪: `tracks`,
  跨: `straddle (v.)`,
  躁: `impetuous`,
  噪: `chirping (n.)`,
  澡: `bath`,
  藻: `algae`,
  燥: `parched`,
  操: `exercise (n.)`,
  猾: `cunning`,
  髓: `marrow`,
  陌: `footpath`,
  隙: `rift (n.)`,
  陡: `steep`,
  陪: `accompany`,
  障: `barrier`,
  隧: `tunnel (n.)`,
  陋: `undesirable`,
  隐: `hidden`,
  陕: `Shaanxi Province`,
  陵: `mausoleum`,
  棱: `edge (n.)`,
  菱: `water caltrop`,
  凌: `bully (v.)`,
  融: `melt`,
  隔: `separate (v.)`,
  窃: `pilfer`,
  挖: `dig (v.)`,
  帘: `drapes`,
  窥: `peep (v.)`,
  穷: `poor`,
  窄: `strait (adj.)`,
  榨: `extract (v.)`,
  窟: `den`,
  窘: `poverty-stricken`,
  窜: `scurry`,
  腔: `body cavity`,
  窝: `hollow (n.)`,
  涡: `whirlpool`,
  锅: `pot`,
  祸: `misfortune`,
  蜗: `snail`,
  宾: `visitor`,
  滨: `water's edge`,
  绷: `stretch taut`,
  纤: `fiber`,
  绰: `ample`,
  绍: `acquaint`,
  纱: `yarn`,
  络: `web`,
  绸: `silk fabric`,
  绒: `down (n.)`,
  绕: `go around`,
  绽: `split at the seams`,
  绵: `continuous`,
  缔: `conclude`,
  纺: `spin (v.)`,
  缠: `wind around`,
  绘: `paint (v.)`,
  纷: `disorderly`,
  绣: `embroidery`,
  缕: `in detail`,
  缩: `shrink (v.)`,
  纳: `let in`,
  综: `sum up`,
  绅: `gentry`,
  绪: `inception`,
  绞: `wring`,
  缓: `unhurried`,
  暖: `warm (adj.)`,
  援: `provide assistance`,
  绢: `tough silk`,
  捐: `contribute`,
  缴: `shell out`,
  邀: `request the presence of`,
  缆: `cable (n.)`,
  哟: `Oh!`,
  颈: `neck (n.)`,
  茎: `plant stem`,
  径: `trail (n.)`,
  劲: `powerful`,
  幼: `young`,
  溪: `creek`,
  幽: `secluded`,
  玄: `mysterious`,
  弦: `bowstring`,
  畜: `livestock`,
  蓄: `save up`,
  磁: `magnetism`,
  滋: `nourish`,
  慈: `kindhearted`,
  累: `tired`,
  螺: `spiral shell`,
  紫: `purple`,
  繁: `numerous`,
  絮: `long-winded`,
  索: `large rope`,
  脖: `head-hinge`,
  勃: `vibrant`,
  卸: `unload`,
  御: `withstand`,
  卵: `nest eggs`,
  孵: `hatch (v.)`,
  乳: `breast`,
  浮: `float (v.)`,
  俘: `captive`,
  榴: `pomegranate`,
  爷: `grandfather`,
  疑: `doubt (v.)`,
  凝: `congeal`,
  玲: `exquisite`,
  铃: `small bell`,
  怜: `pity (v.)`,
  岭: `mountain range`,
  伶: `actor`,
  涌: `gush (v.)`,
  桶: `bucket`,
  诵: `read aloud`,
  范: `model`,
  扼: `clutch (v.)`,
  卷: `exam paper`,
  倦: `worn out`,
  圈: `circle (n.)`,
  怨: `resentment`,
  宛: `winding (adj.)`,
  腕: `wrist`,
  婉: `tactful`,
  碗: `bowl`,
  苍: `ash-colored`,
  抢: `rob`,
  诡: `deceitful`,
  跪: `kneel`,
  舆: `popular`,
  酌: `pour wine`,
  酬: `reward (n./v.)`,
  酷: `brutal`,
  醇: `mellow wine`,
  醋: `vinegar`,
  酱: `thick sauce`,
  奖: `award (n.)`,
  浆: `thick liquid`,
  桨: `oar`,
  蒋: `Jiang`,
  醉: `drunk`,
  碎: `shattered`,
  翠: `emerald green`,
  粹: `unmixed`,
  酸: `sour`,
  梭: `shuttle (n.)`,
  峻: `lofty`,
  俊: `handsome`,
  奠: `found (v.)`,
  蹲: `squat (v.)`,
  逗: `tease (v.)`,
  橱: `closet`,
  嘻: `giggling`,
  嘉: `commend`,
  盟: `alliance`,
  孟: `Mencius`,
  猛: `fierce`,
  盐: `salt (n.)`,
  盔: `helmet`,
  盒: `small box`,
  盛: `flourishing`,
  盏: `small cup`,
  盗: `master thief`,
  磕: `collide with`,
  盈: `replete`,
  盆: `basin`,
  蕴: `amass`,
  鉴: `probe (v.)`,
  滥: `indiscriminate`,
  尴: `abashed`,
  尬: `embarrassed`,
  沈: `Shen`,
  枕: `pillow`,
  耽: `indulge in`,
  衅: `quarrel (n.)`,
  垦: `reclaim`,
  狠: `ruthless`,
  恳: `wholeheartedly`,
  艰: `arduous`,
  爵: `upper crust`,
  嚼: `chew (v.)`,
  卿: `minister`,
  恨: `hate (v.)`,
  朗: `lucent`,
  狼: `wolf`,
  粮: `provisions`,
  酿: `brew (v.)`,
  饥: `starving`,
  饶: `spare (v.)`,
  饰: `ornaments`,
  饮: `beverage`,
  蚀: `eat away`,
  饱: `sated`,
  馒: `bread`,
  饼: `cookie`,
  饺: `dumpling`,
  饿: `hungry`,
  溉: `irrigate`,
  慨: `incensed`,
  苹: `apple`,
  萍: `duckweed`,
  秤: `scale (n.)`,
  淆: `confuse`,
  艾: `Chinese mugwort`,
  哎: `Good grief!`,
  赵: `Zhao`,
  攀: `climb (v.)`,
  刹: `brake (v.)`,
  枫: `maple`,
  钢: `steel`,
  岗: `hillock`,
  纲: `guidelines`,
  屯: `stockpile (v.)`,
  吨: `ton`,
  顿: `pause (n./v.)`,
  纯: `unadulterated`,
  齿: `teeth`,
  龄: `length of service`,
  汹: `turbulent`,
  篱: `fence`,
  仪: `rite`,
  辜: `crime`,
  辞: `phraseology`,
  宰: `butcher (v.)`,
  辨: `differentiate`,
  辫: `braid (n.)`,
  臂: `arm (n.)`,
  劈: `split (v.)`,
  譬: `analogy`,
  僻: `out-of-the-way`,
  纠: `entangle`,
  咳: `cough (v.)`,
  嚷: `cry out`,
  镶: `inlay (v.)`,
  塞: `stronghold`,
  寨: `stockade`,
  晴: `sunny`,
  猜: `guess`,
  靖: `pacify`,
  债: `debt`,
  牲: `domestic animal`,
  隆: `impressive`,
  腥: `fishy smell`,
  猩: `orangutan`,
  醒: `awaken`,
  涛: `longevity`,
  畴: `farmland`,
  铸: `large waves`,
  祷: `cast (v.)`,
  筹: `pray`,
  伺: `make arrangements`,
  契: `contract (n.)`,
  拜: `adore`,
  锋: `cutting edge`,
  逢: `chance upon`,
  缝: `sew`,
  蓬: `disheveled`,
  篷: `awning`,
  蜂: `bee`,
  峰: `peak (n.)`,
  瞎: `visionless`,
  辖: `administer`,
  豁: `breach (n.)`,
  韩: `Korea`,
  违: `disobey`,
  纬: `latitude`,
  奏: `play an instrument`,
  凑: `gather together`,
  秦: `Qin`,
  蠢: `foolish`,
  泽: `swamp (n.)`,
  译: `translate`,
  择: `select (v.)`,
  捧: `carry in both hands`,
  砖: `brick`,
  唾: `saliva`,
  吟: `recite`,
  贪: `greedy`,
  琴: `stringed instrument`,
  炼: `refine`,
  晒: `bask`,
  洒: `spill (v.)`,
  栖: `perch (v.)`,
  栗: `chestnut`,
  牺: `sacrifice (v.)`,
  潭: `deep pool`,
  覆: `overturn`,
  飘: `flutter (v.)`,
  献: `donate`,
  阔: `broad`,
  润: `moisten`,
  阁: `cabinet`,
  搁: `put aside`,
  闹: `stir up trouble`,
  阅: `peruse`,
  闷: `stuffy`,
  闭: `close (v.)`,
  闪: `flash (v.)`,
  阀: `valve`,
  闸: `floodgate`,
  阐: `explicate`,
  涧: `ravine`,
  菲: `humble (adj.)`,
  辈: `lifetime`,
  悲: `sad`,
  徘: `irresolute`,
  喉: `gullet`,
  猴: `monkey`,
  肝: `liver`,
  刊: `publication`,
  奸: `adultery`,
  汗: `sweat (n.)`,
  杆: `shaft`,
  轩: `veranda`,
  罕: `rarely`,
  竿: `pole`,
  悍: `bold`,
  吁: `plead`,
  涂: `smear (v.)`,
  叙: `recount (v.)`,
  徐: `slowly`,
  斜: `slanting`,
  喇: `flared horn`,
  嗽: `hack (v.)`,
  赖: `rely on`,
  懒: `lazy`,
  嫩: `tender (adj.)`,
  董: `director`,
  疗: `cure (v.)`,
  痰: `phlegm`,
  症: `disease`,
  疼: `hurt (v.)`,
  痒: `itch (v.)`,
  瘫: `paralysis`,
  疫: `epidemic`,
  癌: `cancer`,
  疲: `fatigued`,
  痴: `idiotic`,
  瘤: `tumor`,
  疮: `sore (n.)`,
  疾: `rapid`,
  瘾: `addiction`,
  痕: `trace (n.)`,
  汇: `converge`,
  框: `rectangular frame`,
  筐: `rectangular basket`,
  砸: `smash (v.)`,
  匠: `artisan`,
  匪: `bandit`,
  匿: `keep out of sight`,
  兜: `pocket`,
  巨: `gigantic`,
  柜: `cupboard`,
  渠: `canal`,
  拒: `refuse (v.)`,
  矩: `square (n.)`,
  距: `distance`,
  殴: `hit (v.)`,
  呕: `vomit (v.)`,
  躯: `human body`,
  昂: `hold one's head high`,
  抑: `curb (v.)`,
  葵: `large-flowered plants`,
  瞪: `glare (v.)`,
  凳: `bench`,
  澄: `transparent`,
  僚: `coworker`,
  拨: `allocate`,
  泼: `splash (v.)`,
  拔: `pull out`,
  杉: `fir tree`,
  彬: `well-mannered`,
  衫: `shirt`,
  彰: `manifest (adj.)`,
  膨: `puffy`,
  渗: `seep`,
  诊: `diagnose`,
  趁: `take advantage of`,
  寥: `deserted`,
  谬: `wrong (adj.)`,
  铲: `small shovel`,
  萨: `Samoa`,
  刘: `Liu`,
  坟: `tomb`,
  纹: `design (n.)`,
  斋: `abstain from food`,
  斑: `speck`,
  剂: `pharmaceutical (n.)`,
  挤: `squeeze (v.)`,
  脊: `backbone`,
  函: `letter`,
  涵: `culvert`,
  映: `reflect`,
  殃: `calamity`,
  秧: `youngling`,
  焕: `glowing`,
  肥: `plump`,
  爬: `crawl (v.)`,
  疤: `scar (n.)`,
  甜: `sugary`,
  嵌: `set (v.)`,
  钳: `pliers`,
  媒: `matchmaker`,
  煤: `coal`,
  谋: `scheme (v.)`,
  棋: `chess`,
  欺: `dupe (v.)`,
  旗: `flag (n.)`,
  嘶: `hoarse`,
  撕: `rip (v.)`,
  堪: `tolerate`,
  勘: `survey (v.)`,
  遣: `dispatch (v.)`,
  谴: `censure (v.)`,
  囊: `sack (n.)`,
  溃: `burst (v.)`,
  宜: `fitting (adj.)`,
  谊: `friendship`,
  租: `rent (n./v.)`,
  粗: `coarse`,
  阻: `block (v.)`,
  桑: `mulberry tree`,
  嗓: `voicebox`,
  叠: `heap (v.)`,
  锄: `hoe (n./v.)`,
  碰: `bump (v.)`,
  谱: `musical score`,
  壶: `kettle`,
  凿: `bore a hole`,
  湿: `wet`,
  哑: `mute (adj.)`,
  晋: `promote`,
  哄: `fool (v.)`,
  洪: `deluge`,
  烘: `warm by a fire`,
  戴: `have on`,
  翼: `wings`,
  恭: `respectful`,
  拱: `arch (n./v.)`,
  撰: `compose`,
  粪: `dung`,
  殿: `ceremonial hall`,
  暴: `violent`,
  瀑: `waterfall`,
  爆: `explode`,
  拥: `hug (v.)`,
  佣: `put to work`,
  甩: `fling (v.)`,
  庸: `mediocre`,
  触: `touch (v.)`,
  蟹: `crab (n.)`,
  懈: `lax`,
  册: `Vol.`,
  删: `delete`,
  栅: `palisade`,
  珊: `coral`,
  遍: `everywhere`,
  偏: `partial`,
  抵: `resist`,
  氓: `hoodlum`,
  哺: `breastfeed`,
  浦: `river mouth`,
  蒲: `cattail`,
  薄: `slight (adj.)`,
  铺: `shop (n.)`,
  捕: `capture`,
  敷: `apply`,
  脯: `shoulder to wrist`,
  傅: `mentor`,
  缚: `bind fast`,
  簿: `register (n.)`,
  郁: `depressed`,
  郭: `outer walls`,
  廓: `limitless`,
  邓: `Deng`,
  鄙: `despicable`,
  耶: `Jerusalem`,
  邮: `post (v.)`,
  邦: `nation`,
  绑: `truss (v.)`,
  郊: `outskirts`,
  邻: `neighbor`,
  廊: `hallway`,
  缎: `satin`,
  刁: `wily`,
  叼: `hold in the mouth`,
  钙: `calcium`,
  寿: `ardent`,
  饲: `attend to`,
  舶: `rear (v.)`,
  航: `linter`,
  舱: `warship`,
  艇: `navigate`,
  舵: `rudder`,
  沿: `ship's cabin`,
  舰: `light boat`,
  铅: `along (prep.)`,
  殷: `lead (n.)`,
  狐: `fox`,
  瓣: `petal`,
  溢: `brim over`,
  隘: `pass (n.)`,
  霞: `red sky`,
  氨: `ammonia`,
  氧: `oxygen`,
  氛: `atmosphere`,
  氢: `hydrogen`,
  氯: `chlorine`,
  霸: `tyrant`,
  靴: `boots`,
  鞭: `whip (n./v.)`,
  鞠: `bow respectfully`,
  芽: `sprout (n.)`,
  讶: `surprised`,
  雅: `polished`,
  邪: `wicked`,
  悉: `be informed`,
  毯: `blanket (n.)`,
  毫: `milli-`,
  耗: `consume`,
  耕: `till (v.)`,
  籍: `records`,
  藉: `in disorder`,
  畏: `be afraid of`,
  喂: `Hello...`,
  胀: `bloated`,
  帐: `tent`,
  誉: `reputation`,
  剑: `saber`,
  敛: `restrain`,
  捡: `pick up (v.)`,
  俭: `thrifty`,
  签: `sign (v.)`,
  鹏: `roc`,
  鸣: `twitter (v.)`,
  鸿: `swan`,
  莺: `oriole`,
  鸽: `pigeon`,
  鹤: `crane`,
  鹊: `magpie`,
  鸥: `gull`,
  鹅: `goose`,
  鸦: `raven`,
  乌: `crow`,
  呜: `zoom-zoom`,
  捣: `pound with a pestle`,
  寓: `residence`,
  愚: `pea-brained`,
  偶: `by chance`,
  缸: `vat`,
  窑: `kiln`,
  罐: `jar`,
  灌: `pour into`,
  陶: `pottery`,
  淘: `wash in a container`,
  掏: `draw out`,
  谣: `rumor`,
  冤: `injstice`,
  挽: `tow (v.)`,
  勉: `strive`,
  馋: `gluttonous`,
  橡: `rubber tree`,
  豫: `pleased`,
  码: `numeral`,
  驯: `tame (adj./v.)`,
  玛: `Matteo`,
  驻: `be stationed`,
  骄: `arrogant`,
  驰: `gallop (v.)`,
  蚂: `leech-hopper`,
  驶: `maneuver (v.)`,
  骚: `disturb`,
  驾: `drive (v.)`,
  驴: `donkey`,
  腾: `take flight`,
  骡: `mule`,
  骤: `trot (v.)`,
  闯: `rush (v.)`,
  驱: `drive away`,
  驳: `refute`,
  骗: `cheat (v.)`,
  唬: `bluff`,
  虏: `take captive`,
  虐: `despotic`,
  滤: `filter (v.)`,
  瞬: `instant`,
  麟: `Chinese unicorn`,
  磷: `phosphorous`,
  唇: `lips`,
  辱: `disgrace (n./v.)`,
  震: `quake (v.)`,
  振: `vibrate`,
  郑: `Zheng`,
  掷: `hurl`,
  魄: `vigor`,
  槐: `scholar tree`,
  魅: `enchant`,
  瑰: `marvelous`,
  魂: `soul`,
  愧: `ashamed`,
  魁: `leader`,
  胧: `hazy`,
  垄: `raised path between fields`,
  宠: `dote on`,
  庞: `huge`,
  拢: `draw near`,
  聋: `deaf`,
  笼: `cage (n.)`,
  挪: `transfer (v.)`,
  辆: `vehicles`,
  瞒: `dissemble`,
  龟: `tortoise`,
  蝇: `flies`,
  绳: `rope (n.)`,
  淹: `inundate`,
  俺: `we (exclusive)`,
  钮: `push button (n.)`,
  羞: `shy`,
  纽: `New York`,
  赫: `illustrious`,
  奕: `radiating vitality`,
  迹: `indication`,
  蛮: `barbaric`,
  啤: `beer`,
  脾: `spleen`,
  碑: `stele`,
  嘱: `admonish`,
  肆: `IV`,
  插: `insert (v.)`,
  毁: `ruin (v.)`,
  鼠: `mouse`,
  舅: `mother's brother`,
  滔: `surging`,
  稻: `unhulled rice`,
  蹈: `tread (v.)`,
  嫂: `elder brother's wife`,
  搜: `search (v.)`,
  瘦: `emaciated`,
  艘: `vessels`,
  焰: `flame (n.)`,
  馅: `filling`,
  陷: `get stuck`,
  爽: `frank (adj.)`,
  缀: `embellish`,
  傻: `thick-headed`,
  蝴: `butterfly (front end)`,
  蝶: `butterfly (back end)`,
  蜘: `spider (front end)`,
  蛛: `spider (back end)`,
  骆: `camel (front end)`,
  驮: `camel (back end)`,
  蜻: `dragonfly (front end)`,
  蜓: `dragonfly (back end)`,
  凤: `male phoenix`,
  凰: `female phoenix`,
  玻: `glass (front side)`,
  璃: `glass (back side)`,
  橄: `olive (A)`,
  榄: `olive (B)`,
  芙: `hibiscus (A)`,
  蓉: `cottonrose hibiscus (B)`,
  咖: `coffee (first drop)`,
  啡: `coffee (last drop)`,
  葡: `grapes (A)`,
  萄: `grapes (B)`,
  蘑: `mushroom (cap)`,
  菇: `mushroom (stem)`,
  吩: `in-`,
  咐: `-struct`,
  乒: `ping`,
  乓: `pong`,
  曹: `Cao`,
  潘: `Pan`,
  谭: `Tan`,
  姚: `Yao-2`,
  薛: `Xue`,
  彭: `Peng`,
  冯: `Feng`,
  魏: `Wei`,
  岳: `Yue`,
  莉: `jasmine`,
  湘: `Hunan Province`,
  甸: `outlying areas`,
  沧: `dark blue`,
  穆: `reverent`,
  娜: `na`,
  琼: `fine jade`,
  琳: `gem`,
  钧: `30 catties`,
};
